version: '3.4'

services:
  server:
    build:
      context: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/usr/src/server'
      - 'app_dependencies:/usr/src/server/node_modules'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

volumes:
  app_dependencies: